version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.9"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: requirements/requirements-optionals.txt
    - requirements: requirements/requirements-documentation.txt
    - method: pip
      path: .
