# Generated by Django 2.1 on 2018-10-13 09:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_auto_20180922_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_start_date', models.DateField(blank=True, default=None, null=True)),
                ('effective_end_date', models.DateField(blank=True, default=None, null=True)),
                ('last_mod_user_name', models.CharField(max_length=80)),
                ('last_mod_date', models.DateField(auto_now=True)),
                ('school_bulletin_prefix_code', models.CharField(max_length=10)),
                ('suffix_two', models.CharField(max_length=2)),
                ('subject_area_code', models.CharField(max_length=10)),
                ('course_number', models.CharField(max_length=10)),
                ('course_identifier', models.CharField(max_length=10, unique=True)),
                ('course_name', models.CharField(max_length=80)),
                ('course_description', models.TextField()),
            ],
            options={
                'ordering': ['course_number'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('effective_start_date', models.DateField(blank=True, default=None, null=True)),
                ('effective_end_date', models.DateField(blank=True, default=None, null=True)),
                ('last_mod_user_name', models.CharField(max_length=80)),
                ('last_mod_date', models.DateField(auto_now=True)),
                ('term_identifier', models.TextField(max_length=10)),
                ('audit_permitted_code', models.PositiveIntegerField(blank=True, default=0)),
                ('exam_credit_flag', models.BooleanField(default=True)),
                ('course', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='example.Course')),
            ],
            options={
                'ordering': ['term_identifier'],
            },
        ),
    ]
