# Generated by Django 4.0 on 2021-12-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("example", "0010_auto_20210714_0809"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="type",
            new_name="author_type",
        ),
        migrations.AlterField(
            model_name="project",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
    ]
