# Generated by Django 4.2.5 on 2023-09-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("example", "0012_author_full_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("questions", models.JSONField()),
            ],
        ),
    ]
