# Generated by Django 6.0.7 on 2026-10-08 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0014_questionnaire_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="current_project",
        ),
        migrations.RemoveField(
            model_name="company",
            name="future_projects",
        ),
        migrations.RemoveField(
            model_name="labresults",
            name="author",
        ),
        migrations.RemoveField(
            model_name="labresults",
            name="research_project",
        ),
        migrations.RemoveField(
            model_name="project",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="project",
            name="project_type",
        ),
        migrations.RemoveField(
            model_name="researchproject",
            name="project_ptr",
        ),
        migrations.DeleteModel(
            name="ArtProject",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="LabResults",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="ResearchProject",
        ),
    ]
